app/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(128))
    tasks = db.relationship('Task', backref='author', lazy='dynamic')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(200), nullable=False)
    completed = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<Task {self.id}>'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError
from .models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                'That username is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()
# 'main.login' will be the name of our login route
login_manager.login_view = 'main.login'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '8w5h4J2k9L7p6T1s3G0q8R5f4P9x7M1n0B3v2C6z4Y8d0E9u7'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'

    db.init_app(app)

    login_manager.init_app(app)

    # User loader function for Flask-Login
    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from .routes import main_blueprint
    app.register_blueprint(main_blueprint)

    from . import models
    with app.app_context():
        db.create_all()

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .models import Task, db, User
from .forms import RegistrationForm, LoginForm
from flask_login import login_user, logout_user, login_required, current_user

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        task_content = request.form['content']
        new_task = Task(content=task_content, author=current_user)
        try:
            db.session.add(new_task)
            db.session.commit()
            return redirect(url_for('main.home'))
        except:
            return 'There was an issue adding your task'

    tasks = Task.query.filter_by(
        user_id=current_user.id).order_by(Task.id).all()

    return render_template('index.html', tasks=tasks)


@main_blueprint.route('/delete/<int:id>', methods=['POST'])
def delete_task(id):
    task_to_delete = Task.query.get_or_404(id)
    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect(url_for('main.home'))
    except:
        return 'There was a problem deleting that task'


@main_blueprint.route('/complete/<int:id>', methods=['POST'])
def complete_task(id):
    task = Task.query.get_or_404(id)
    task.completed = not task.completed
    try:
        db.session.commit()
        return redirect(url_for('main.home'))
    except:
        return 'There was an issue updating your task'


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Account created successfully! You can now log in.', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in successfully.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Task App - {{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Task App</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1 class="text-center">My Tasks</h1>

            <form action="{{ url_for('main.home') }}" method="POST" class="mb-3">
                <div class="input-group">
                    <input type="text" name="content" id="content" class="form-control" placeholder="Enter a new task">
                    <button type="submit" class="btn btn-primary">Add Task</button>
                </div>
            </form>

            <ul class="list-group">
                {% for task in tasks %}
                <li
                    class="list-group-item d-flex justify-content-between align-items-center {% if task.completed %}list-group-item-success{% endif %}">
                    <span {% if task.completed %}style="text-decoration: line-through;" {% endif %}>{{ task.content
                        }}</span>
                    <div>
                        <form action="{{ url_for('main.complete_task', id=task.id) }}" method="POST"
                            style="display: inline;">
                            <button type="submit"
                                class="btn {% if task.completed %}btn-warning{% else %}btn-success{% endif %} btn-sm">
                                {% if not task.completed %}Complete{% else %}Incomplete{% endif %}
                            </button>
                        </form>
                        <form action="{{ url_for('main.delete_task', id=task.id) }}" method="POST"
                            style="display: inline;" onsubmit="return confirm('Are you sure you want to delete this task?');">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1 class="text-center">{{ title }}</h1>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.username.label(class="form-label") }}
                    {{ form.username(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(class="form-control") }}
                </div>
                <div class="text-center">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1 class="text-center">{{ title }}</h1>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.username.label(class="form-label") }}
                    {{ form.username(class="form-control") }}
                    {% for error in form.username.errors %}
                    <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
                    {{ form.password(class="form-control") }}
                    {% for error in form.password.errors %}
                    <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    {{ form.confirm_password.label(class="form-label") }}
                    {{ form.confirm_password(class="form-control") }}
                    {% for error in form.confirm_password.errors %}
                    <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="text-center">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}